BOARD_TAG    = trinket5
ARDUINO_LIBS = FastLED
MONITOR_PORT = $(shell ./find_device)
FORCE_MONITOR_PORT = 1
ARDUINO_SKETCHBOOK = /home/ryan/Arduino
ALTERNATE_CORE_PATH = /home/ryan/Arduino/hardware/attiny

AVRDUDE_ARD_PROGRAMMER = usbtiny
AVRDUDE_ARD_BAUDRATE = 57600

RESET_CMD = true

include /home/ryan/src/Arduino-Makefile/Arduino.mk
