BOARD_TAG    = teensyLC
ARDUINO_LIBS = FastLED
#ARDUINO_SKETCHBOOK = /home/ryan/arduino/arduino-1.6.12
ARDUINO_DIR = /home/ryan/arduino/arduino-1.6.12

include /home/ryan/src/Arduino-Makefile/Teensy.mk
